language: node_js
node_js:
  - 10.16.0
jobs:
  include:
    - stage: test
      script:
        - npm run cover
        - npx codecov
        - cat ./build/coverage/lcov.info | npx coveralls
      node_js:
        - 14.11.0
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        cleanup: 'false'
        script:
          - npx semantic-release
before_script:
  - npm prune
  - npm install -g --production coveralls codecov
after_script:
  - codecov
  - cat ./build/coverage/lcov.info | coveralls
  - npm run docs
script:
  - npm run cover
branches:
  only:
    - master
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
notifications:
  email:
    - markus.felten@gmx.de
after_success:
  - npm run semantic-release
before_install:
  - npm i -g npm@latest
cache: npm
